name: Build archiso on arch
on: workflow_dispatch

jobs:
  build-archiso:
    name: Build the iso
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: ./archiso/mkarchiso -w ./work-dir -o ./out_dir ./configs/releng

      - name: Upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: Iso
          path: ./out_dir/*.iso
