name: Build archiso on arch
on: workflow_dispatch

jobs:
  build-archiso:
    name: Build the iso
    runs-on: ubuntu-latest
    steps:
      - uses: RangHo/setup-arch@main
        with:
          version: latest
          mirror: https://geo.mirror.pkgbuild.com
          packages: ""
      - name: Install packages
        shell: arch.sh {0}
        run: sudo pacman --noconfirm -Sy mtools dosfstools grub squashfs-tools
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        shell: arch.sh {0}
        run: sudo ./archiso/mkarchiso -v -w ./work-dir -o ./out_dir ./configs/releng

      - name: Upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: Iso
          path: ./out_dir/*.iso
